# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
  - go mod tidy
builds:
- id: pbcopy
  main: ./cmd/pbcopy
  binary: pbcopy
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - amd64
archives:
- replacements:
    linux: Linux
    amd64: x86_64
  files:
  - README.md
  - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
    - go mod tidy
brews:
- name: pbcopy
  tap:
    owner: bottlerocketlabs
    name: homebrew-apps
    token: "{{ .Env.HOMEBREW_GITHUB_TOKEN }}"
  folder: Formula
  homepage:  https://github.com/bottlerocketlabs/remote-pbcopy
  description: pbcopy for linux that works in the terminal over ssh
  license: MIT
  test: |
    system "#{bin}/pbcopy -h"
  dependencies:
  - name: go
  install: |-
    bin.install "pbcopy"
